apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  labels:
    app: airflow
    component: config
data:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow