apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-postgres-env
  labels:
    app: airflow
    component: config
data:
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
  POSTGRES_DB: airflow