apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  labels:
    app: airflow
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: postgres
  template:
    metadata:
      labels:
        app: airflow
        component: postgres
    spec:
      containers:
        - name: airflow-postgres
          image: postgres:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-volume
              mountPath: /var/lib/postgresql/data
          envFrom:
            - configMapRef:
                name: airflow-postgres-env
      volumes:
        - name: postgres-db-volume
          persistentVolumeClaim:
            claimName: airflow-postgres-pvc