apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      initContainers:
        - name: chown
          image: apache/airflow:2.10.5
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
            - chown -R 50000:0 /opt/airflow/dags /opt/airflow/logs
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: /opt/airflow/logs
        - name: check-migrations
          image: apache/airflow:2.10.5
          imagePullPolicy: IfNotPresent
          args:
            - db
            - check-migrations
          envFrom:
            - configMapRef:
                name: airflow-env
      containers:
        - name: airflow-scheduler
          image: apache/airflow:2.10.5
          imagePullPolicy: IfNotPresent
          args:
            - scheduler
          envFrom:
            - configMapRef:
                name: airflow-env
          volumeMounts:
            - name: airflow-dags
              mountPath: /opt/airflow/dags
            - name: airflow-logs
              mountPath: /opt/airflow/logs
      volumes:
        - name: airflow-dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc