apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  labels:
    app: airflow
    component: postgres
spec:
  selector:
    app: airflow
    component: postgres
  type: NodePort
  ports:
    - port: 5432