apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  selector:
    app: airflow
    component: webserver
  type: NodePort
  ports:
    - port: 8080