apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dags-pv
  labels:
    app: airflow
    component: dags
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data/airflow/dags
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  labels:
    app: airflow
    component: dags
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: manual